name: Ruby

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 2.6, truffleruby, truffleruby-head ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: sudo apt-get update
    - run: sudo apt-get install libsqlite3-dev libxml2-dev libxslt-dev
    - run: gem install 'capybara'
    - run: gem install 'cucumber'
    - run: ruby test.rb
